# Part 2. Vector and Matrix

In this lab, we will learn how to use Python to operate vectors and matrices. 

## 1. Example

### 1.1 Load data with pandas

In [21]:
import numpy as np
import pandas as pd

# load data with pandas
df = pd.read_csv('cars.csv')
# print(df)

# convert a pandas dataframe to a numpy array
X = df.values[:, 1:-1]
print(type(X))
print(X.shape)
print(X)

<class 'numpy.ndarray'>
(406, 7)
[[18.0 8 307.0 ... 3504 12.0 70]
 [15.0 8 350.0 ... 3693 11.5 70]
 [18.0 8 318.0 ... 3436 11.0 70]
 ...
 [32.0 4 135.0 ... 2295 11.6 82]
 [28.0 4 120.0 ... 2625 18.6 82]
 [31.0 4 119.0 ... 2720 19.4 82]]


### 1.2 Operation for vector

In [22]:
#Get first row and the second to last row

x1 = X[0, :]
x2 = X[-2, :]

print(x1)
print(x2)

# Addition

y = x1 + x2
print(y)

[18.0 8 307.0 130 3504 12.0 70]
[28.0 4 120.0 79 2625 18.6 82]
[46.0 12 427.0 209 6129 30.6 152]


### 1.3 Operation for matrix

In [23]:
# Get first 5 rows and last 5 rows 

m1 = X[0:5, :]
m2 = X[-5:, :]

print(m1)
print(m2)

# Subtraction
m = m1 - m2
print(m)

[[18.0 8 307.0 130 3504 12.0 70]
 [15.0 8 350.0 165 3693 11.5 70]
 [18.0 8 318.0 150 3436 11.0 70]
 [16.0 8 304.0 150 3433 12.0 70]
 [17.0 8 302.0 140 3449 10.5 70]]
[[27.0 4 140.0 86 2790 15.6 82]
 [44.0 4 97.0 52 2130 24.6 82]
 [32.0 4 135.0 84 2295 11.6 82]
 [28.0 4 120.0 79 2625 18.6 82]
 [31.0 4 119.0 82 2720 19.4 82]]
[[-9.0 4 167.0 44 714 -3.5999999999999996 -12]
 [-29.0 4 253.0 113 1563 -13.100000000000001 -12]
 [-14.0 4 183.0 66 1141 -0.5999999999999996 -12]
 [-12.0 4 184.0 71 808 -6.600000000000001 -12]
 [-14.0 4 183.0 58 729 -8.899999999999999 -12]]


## 2 Task

### 2.1 Get the first column and the second to last column from X

In [24]:
# this is your code to get two vectors

v1 = X[: , 0]
v2 = X[: , -2]
print(v1)
print(v2)

[18.0 15.0 18.0 16.0 17.0 15.0 14.0 14.0 14.0 15.0 0.0 0.0 0.0 0.0 0.0
 15.0 14.0 0.0 15.0 14.0 24.0 22.0 18.0 21.0 27.0 26.0 25.0 24.0 25.0 26.0
 21.0 10.0 10.0 11.0 9.0 27.0 28.0 25.0 25.0 0.0 19.0 16.0 17.0 19.0 18.0
 14.0 14.0 14.0 14.0 12.0 13.0 13.0 18.0 22.0 19.0 18.0 23.0 28.0 30.0
 30.0 31.0 35.0 27.0 26.0 24.0 25.0 23.0 20.0 21.0 13.0 14.0 15.0 14.0
 17.0 11.0 13.0 12.0 13.0 19.0 15.0 13.0 13.0 14.0 18.0 22.0 21.0 26.0
 22.0 28.0 23.0 28.0 27.0 13.0 14.0 13.0 14.0 15.0 12.0 13.0 13.0 14.0
 13.0 12.0 13.0 18.0 16.0 18.0 18.0 23.0 26.0 11.0 12.0 13.0 12.0 18.0
 20.0 21.0 22.0 18.0 19.0 21.0 26.0 15.0 16.0 29.0 24.0 20.0 19.0 15.0
 24.0 20.0 11.0 20.0 21.0 19.0 15.0 31.0 26.0 32.0 25.0 16.0 16.0 18.0
 16.0 13.0 14.0 14.0 14.0 29.0 26.0 26.0 31.0 32.0 28.0 24.0 26.0 24.0
 26.0 31.0 19.0 18.0 15.0 15.0 16.0 15.0 16.0 14.0 17.0 16.0 15.0 18.0
 21.0 20.0 13.0 29.0 23.0 20.0 23.0 24.0 25.0 24.0 18.0 29.0 19.0 23.0
 23.0 22.0 25.0 33.0 28.0 25.0 25.0 26.0 27.0 17.5 16.0 15.5 14.5 22.0

### 2.2 Perform following operations on these two vectors and print the result

In [25]:
v1 = X[: , 0]
v2 = X[: , -2]

# 1. addition and subtraction

AddVector = v1 + v2

print(AddVector)
print("\n")

SubVector = v1 - v2

print(SubVector)
print("\n")

# 2. element-wise multiplication

MultVector = v1 * v2
print(MultVector)
print("\n")

# 3. inner product
Vector1 = np.array(v1)
Vector2 = np.array(v2)
print("inner product: {}".format(np.inner(Vector1, Vector2)))
print("\n")

# 4. three norms
print("Three Norms of Vector 1")
print("l1 norm: {}".format(np.linalg.norm(Vector1, ord=1)))
print("l2 norm: {}".format(np.linalg.norm(Vector1, ord=2)))
print("max-norm: {}".format(np.linalg.norm(Vector1, ord=np.inf)))
print("\n")


print("Three Norms of Vector 2 ")
print("l1 norm: {}".format(np.linalg.norm(Vector2, ord=1)))
print("l2 norm: {}".format(np.linalg.norm(Vector2, ord=2)))
print("max-norm: {}".format(np.linalg.norm(Vector2, ord=np.inf)))
print("\n")

# 5. compute the distance between these two vectors

print("distance: {}".format(np.linalg.norm(Vector1 - Vector2, ord=2)))

[30.0 26.5 29.0 28.0 27.5 25.0 23.0 22.5 24.0 23.5 17.5 11.5 11.0 10.5
 11.0 25.0 22.0 8.0 24.5 24.0 39.0 37.5 33.5 37.0 41.5 46.5 42.5 38.5 42.5
 38.5 36.0 24.0 25.0 24.5 27.5 41.5 43.5 39.0 44.0 20.0 32.0 31.5 32.5
 34.5 33.5 26.0 25.5 27.5 27.0 23.5 25.0 25.0 31.5 41.0 34.0 32.5 37.0
 42.0 49.5 44.5 50.0 53.0 46.0 46.5 39.5 42.0 46.5 39.5 37.5 25.0 26.0
 28.5 27.0 28.5 22.0 26.5 25.5 25.5 32.5 27.5 27.0 29.0 28.0 32.5 40.0
 40.5 44.0 38.0 45.0 37.5 43.0 43.5 26.0 25.5 26.0 28.5 27.5 23.5 25.0
 26.0 28.5 24.0 23.0 24.0 34.5 34.0 34.0 34.5 39.0 47.0 25.0 24.5 26.0
 24.5 33.0 39.0 40.5 38.5 31.5 37.5 35.0 41.5 28.0 25.5 48.5 39.5 34.0
 34.5 26.0 38.0 33.5 22.0 36.5 38.0 35.0 32.0 50.0 42.5 53.0 42.0 33.0
 34.0 34.5 30.0 27.5 27.5 30.0 29.5 45.5 41.5 40.5 47.5 51.0 42.5 39.5
 40.0 39.0 41.5 47.0 35.0 34.0 36.0 34.5 27.5 29.0 30.5 27.5 38.0 34.5
 34.0 37.0 36.0 33.5 25.0 45.0 40.0 36.0 41.5 37.5 41.5 41.0 32.5 43.0
 36.0 38.0 40.0 36.5 38.5 50.5 43.5 41.9 39.9 43.7 42.3 30.5 29.0 29.4
 2

### 2.3 Get the first three columns and the last three columns from X

In [26]:
# this is your code to get two matrices: A, B


v1 = X[: , 3]
v2 = X[: , -3]
Vector1 = np.array(v1)
Vector2 = np.array(v2)
print(Vector1)
print(Vector2)

[130 165 150 150 140 198 220 215 225 190 115 165 153 175 175 170 160 140
 150 225 95 95 97 85 88 46 87 90 95 113 90 215 200 210 193 88 90 95 0 48
 100 105 100 88 100 165 175 153 150 180 170 175 110 72 100 88 86 90 70 76
 65 69 60 70 95 80 54 90 86 165 175 150 153 150 208 155 160 190 97 150 130
 140 150 112 76 87 69 86 92 97 80 88 175 150 145 137 150 198 150 158 150
 215 225 175 105 100 100 88 95 46 150 167 170 180 100 88 72 94 90 85 107
 90 145 230 49 75 91 112 150 110 122 180 95 0 100 100 67 80 65 75 100 110
 105 140 150 150 140 150 83 67 78 52 61 75 75 75 97 93 67 95 105 72 72 170
 145 150 148 110 105 110 95 110 110 129 75 83 100 78 96 71 97 97 70 90 95
 88 98 115 53 86 81 92 79 83 140 150 120 152 100 105 81 90 52 60 70 53 100
 78 110 95 71 70 75 72 102 150 88 108 120 180 145 130 150 68 80 58 96 70
 145 110 145 130 110 105 100 98 180 170 190 149 78 88 75 89 63 83 67 78 97
 110 110 48 66 52 70 60 110 140 139 105 95 85 88 100 90 105 85 110 120 145
 165 139 140 68 95 97 75 95 105 85 97 

### 2.4 Perform following operations on these two matrices and print the result

In [33]:
# 1. addition and subtraction 

print("substraction: {}".format(v1-v2))
print("addition: {}".format(v1+v2))


# 2. compute the transpose of the second matrix: C = B^T, and print the shape of C

Vector3 = np.transpose(Vector2)
print("Transposition of B: {}".format(Vector3))
print("Shape of C : {}".format(Vector3.shape))

# 3. compute the product between A and C, and print the result and its shape

Vector4 = Vector1 * Vector3
print("Product of A and C: {}".format(Vector4))
print("Shape of Product: {}".format(Vector4.shape))
      
# 4. compute the transpose of the first matrix: D = A^T, and print the shape of D
Vector5 = np.transpose(Vector1)
print("Shape of D: {} ".format(Vector5.shape))

# 5. compute the product between D and B, and print the result and its shape
Vector6 = Vector5 * Vector2
print("Product of D and B: {}".format(Vector6))
print("Shape of Product: {}".format(Vector6.shape))


substraction: [-3374 -3528 -3286 -3283 -3309 -4143 -4134 -4097 -4200 -3660 -2975 -3977
 -3881 -3991 -3675 -3393 -3449 -3213 -3611 -2861 -2277 -2738 -2677 -2502
 -2042 -1789 -2585 -2340 -2280 -2121 -2558 -4400 -4176 -4172 -4539 -2042
 -2174 -2133 -2046 -1930 -2534 -3334 -3229 -3214 -3188 -4044 -4289 -4001
 -3946 -4775 -4576 -4965 -2852 -2336 -3182 -3051 -2134 -2033 -2004 -1989
 -1708 -1544 -1774 -1885 -2183 -2046 -2200 -2318 -2140 -4109 -4210 -3985
 -3976 -3522 -4425 -4347 -4296 -4232 -2233 -3742 -3968 -4154 -3927 -2821
 -2435 -2892 -2120 -2309 -2196 -2409 -2084 -2012 -3925 -3522 -3843 -3905
 -3627 -4754 -4314 -4205 -4087 -4520 -4726 -3646 -3016 -3178 -2845 -2933
 -2809 -1904 -4847 -4739 -4484 -4319 -2689 -2191 -2329 -2285 -2034 -2225
 -2365 -2175 -3937 -4048 -1818 -2083 -2491 -2756 -3249 -2550 -2685 -3484
 -3007 -2875 -2801 -3236 -1883 -2371 -1771 -2467 -3681 -3522 -3508 -4001
 -4549 -4307 -4498 -4107 -2136 -1896 -2222 -1597 -1942 -2050 -2033 -2171
 -2392 -2298 -1933 -3169 -3354 -3360 